<?php

/**
 * @file
 * Module file for views_infinite_scroll.
 */

use Drupal\Core\Url;
use Drupal\views_infinite_scroll\Plugin\views\pager\InfiniteScroll;

/**
 * Implements hook_preprocess_views_infinite_scroll_pager().
 */
function views_infinite_scroll_preprocess_views_infinite_scroll_pager(&$vars) {
  // The important parts we needed lifted wholesale from
  // template_preprocess_views_mini_pager().
  global $pager_page_array, $pager_total;
  $element = $vars['element'];
  $parameters = $vars['parameters'];
  if ($pager_page_array[$element] < ($pager_total[$element] - 1)) {
    $options = array(
      'query' => pager_query_add_page($parameters, $element, $pager_page_array[$element] + 1),
    );
    $vars['items']['next']['href'] = Url::fromRoute('<current>', [], $options);
  }
  // tbf, sort out better object type...
  $vars['analytics']['ip'] = $_SERVER['REMOTE_ADDR'];
  $vars['analytics']['lang'] = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);
  $vars['analytics']['agent'] = $_SERVER['HTTP_USER_AGENT'];
  $vars['analytics']['url'] = preg_replace('/[^a-zA-Z0-9_ %\[\]\.\(\)%&-]/s', '', $_SERVER['REQUEST_URI']);
  $vars['path'] = $GLOBALS['base_url'];
  $vars['#cache']['contexts'][] = 'url.query_args';
}

/**
 * Implements hook_preprocess_views_view().
 */
function views_infinite_scroll_preprocess_views_view(&$vars) {
  $view = $vars['view'];
  if ($view->getDisplay()->isPagerEnabled()) {
    $pager = $view->getPager();
    if ($pager && $pager instanceof InfiniteScroll) {
      $vars['rows']['#theme_wrappers'] = ['container'];
      $vars['rows']['#attributes'] = ['class' => ['views-infinite-scroll-content-wrapper']];
    }
  }
}
